=== Project-Env/Project-Env/code/core/src/main/resources/ch/repolevedavaj/projectenv/project-env.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="ch.repolevedavaj.projectenv"
           xmlns="ch.repolevedavaj.projectenv">

    <xs:complexType name="baseInstallationConfiguration">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element name="download-uris">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element type="xs:string" name="macos" minOccurs="0"/>
                        <xs:element type="xs:string" name="windows" minOccurs="0"/>
                        <xs:element type="xs:string" name="linux" minOccurs="0"/>
                        <xs:element type="xs:string" name="system-independent" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="exports" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="export" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element type="xs:string" name="name"/>
                                    <xs:element type="xs:string" name="value"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="path-elements" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element type="xs:string" name="path-element" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="post-installation-commands" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="post-installation-command" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element type="xs:string" name="executable"/>
                                    <xs:element name="arguments">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element type="xs:string" name="argument" maxOccurs="unbounded"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="jdkInstallationConfiguration">
        <xs:complexContent>
            <xs:extension base="baseInstallationConfiguration"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="mavenInstallationConfiguration">
        <xs:complexContent>
            <xs:extension base="baseInstallationConfiguration"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="nodeInstallationConfiguration">
        <xs:complexContent>
            <xs:extension base="baseInstallationConfiguration"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="genericToolInstallationConfiguration">
        <xs:complexContent>
            <xs:extension base="baseInstallationConfiguration"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="project-env">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tools">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="directory"/>
                            <xs:element name="installers">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="jdkInstallationConfiguration" name="jdk"
                                                    minOccurs="0"/>
                                        <xs:element type="mavenInstallationConfiguration" name="maven"
                                                    minOccurs="0"/>
                                        <xs:element type="nodeInstallationConfiguration" name="node"
                                                    minOccurs="0"/>
                                        <xs:element type="genericToolInstallationConfiguration" name="generic"
                                                    minOccurs="0"
                                                    maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="shell-integration">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="profile"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Project-Env/Project-Env/project-env.xml
<?xml version="1.0" encoding="UTF-8"?>
<project-env xmlns="ch.repolevedavaj.projectenv"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="ch.repolevedavaj.projectenv src/main/resources/ch/repolevedavaj/projectenv/project-env.xsd">
    <tools>
        <directory>.tools</directory>
        <installers>
            <jdk>
                <name>jdk</name>
                <download-uris>
                    <macos>https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jdk_x64_mac_hotspot_11.0.9.1_1.tar.gz</macos>
                    <windows>https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.9.1_1.zip</windows>
                    <linux>https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.9.1_1.tar.gz</linux>
                </download-uris>
            </jdk>
            <maven>
                <name>maven</name>
                <download-uris>
                    <system-independent>https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz</system-independent>
                </download-uris>
            </maven>
        </installers>
    </tools>
</project-env>
